name: SSE CI/CD v2.0.0
on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: "Install style checker (clang)"
        run: sudo apt update -y && sudo apt-get install -y clang-format
      - name: "Run style checker"
        run: clang-format -n -Werror src/* tests/*

  build_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: "Install required packages"
        run: sudo apt update -y && sudo apt-get install -y cmake libyaml-cpp-dev libeigen3-dev libboost-test-dev
      - name: "Build packages"
        run: mkdir build && cd build && cmake .. && make

  test:
    runs-on: ubuntu-latest
    needs: build_package
    steps:
      - uses: actions/checkout@v3.3.0
      - name: "Install required packages"
        run: sudo apt update -y && sudo apt-get install -y cmake libyaml-cpp-dev libeigen3-dev libboost-test-dev
      - name: "Build packages"
        run: mkdir build && cd build && cmake .. && make
      - name: "run tests"
        run: cd build && make test
